baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ubucon Asia 2021"
theme = "ubuconasia"
Paginate = 5
buildFuture = true

[params]
    description = "First Ubuntu conference in Asia organized by Ubuntu Local Communities in Asian region."
    period = "Expected to take place in 2021 Q3 or Q4"